// eslint-disable-next-line import/no-anonymous-default-export
export default {
  ChainNotYetSupported: new Error('Chain is not yet supported'),
  RequestTimeout: new Error('Request timed out'),
  RequestFailed: (cause: unknown) => new Error('Request failed', { cause }),
  InvalidResponse: new Error('Invalid response'),
  InvalidAccount: new Error('Account needed to perform this action'),
  ManagerNotReady: new Error('Manager not ready'),
  MethodNotImplemented: new Error('Method not implemented'),
  NoWalletDetected: new Error('No wallet detected'),
  ConnectYourWallet: new Error('Connect your wallet'),
  InstanceNotFound: new Error('Instance not found'),
  FunctionNotFound: new Error('Function not found'),
  WebsiteNotFound: new Error('Website not found'),
  VolumeNotFound: new Error('Volume not found'),
  SSHKeyNotFound: new Error('SSH key not found'),
  DomainNotFound: new Error('Domain not found'),
  InvalidStreamCost: new Error('Invalid stream cost'),
  InvalidNode: new Error('Invalid node'),
  UnknownType: new Error('Unknown type'),
  ValidationError: new Error('Validation error, check highlighted form fields'),
  FieldError: (field: string, description?: string) =>
    new Error(`Error on field "${field}": ${description}`),
  NotificationsNotReady: new Error('Notifications not ready'),
  InvalidCodeFile: new Error('Invalid function code file'),
  InvalidCodeType: new Error('Invalid function code type'),
  InvalidCRNAddress: new Error('Invalid CRN address'),
  CustomRuntimeNeeded: new Error('Custom runtime should be added'),
  ReceivedRequired: new Error(
    'Payment receiver is required for stream payments',
  ),
  StreamNotSupported: new Error(
    'Stream payments are only supported on Avalanche',
  ),
}
