name: Manual Bump & Release Trigger

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Type of version bump'
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          npm version ${{ inputs.release-type }}

      - name: Push version commit and tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin HEAD:main
          git push origin --tags
