name: New version release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Type of version bump'
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          npm version ${{ inputs.release-type }}

      - name: Push version commit and tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push origin HEAD:main
          git push origin --tags

  push-to-ipfs:
    needs: bump-version
    runs-on: ubuntu-22.04
    steps:
      - name: Build and Export
        uses: ./.github/actions/build
        with:
          fa-token: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
      - name: Push to IPFS
        uses: ./.github/actions/push_to_ipfs
        with:
          upload-dir: out
