name: Publish

on:
  push:
    branches:
      - main
      - release/**

env:
  IS_GH_PAGES: gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Export
        uses: ./.github/actions/build
        with:
          fa-token: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
